### ISSUE TITLE
Bug: Intermittent error on 'copy-uri-block' 

### ISSUE THREAD

**Issue by chaecramb** [Vinzent03/obsidian-advanced-uri#111]
I quite regularly have to run `copy-uri-block` twice or even three times as it fails the first time. 

It seems to mostly happen when I try to run it via a hotkey too quickly after inputing text. A common situation that triggers it for me is that I want to paste a block somewhere, then immediately copy its uri. Hitting my hotkey too quickly after a paste invariably triggers the error, I need to give it a few seconds. A similar thing happens if I try to copy the block uri immediately after I finish typing.

When it fails it throws the following error.

```Command failed to execute:  obsidian-advanced-uri:copy-uri-block
app.js:1 TypeError: Cannot read properties of undefined (reading 'type')
    at Function.BlockUtils.getBlock (plugin:obsidian-advanced-uri:3262:26)
    at Function.BlockUtils.getBlockId (plugin:obsidian-advanced-uri:3305:30)
    at Object.checkCallback (plugin:obsidian-advanced-uri:4521:53)
    at JN (app.js:1:1504465)
    at e.executeCommand (app.js:1:1505879)
    at e.onTrigger (app.js:1:1229442)
    at e.handleKey (app.js:1:1036799)
    at t.e.handleKey (app.js:1:1036912)
    at t.handleKey (app.js:1:1037121)
    at e.onKeyEvent (app.js:1:1038055)
```

This is Obsidian 1.1.12 and Advanced URI 1.32.3. I've tested in a fresh vault with the same result.

**Comment by Vinzent03** [comment]
That's because Obsidian hasn't parsed and updated the metadata cache yet, which this plugin depends on. There's nothing I can do here, you'll just have to wait a few seconds.
