### ISSUE TITLE
[Bug] Open note URI doesnt work if no note is already open

### ISSUE THREAD

**Issue by csss1234** [Vinzent03/obsidian-advanced-uri#179]
Obsidian 1.6.5
MacOS 14.5
Advanced URI 1.40.1

I haven't tried in sandbox yet, but when I close all tabs I see this on my mac:
![image](https://github.com/Vinzent03/obsidian-advanced-uri/assets/45954264/d1829470-c4d5-4ca2-83ea-2ab2787142d2)

If i click on a link outside of obsidian like `obsidian://advanced-uri?vault=Vault&uid= xxxxx-xxxxx-xxxxx-xxxxx-xxxxx`, nothing happens. I have to have a note open in an existing tab for it to work as expected

**Comment by Vinzent03** [comment]
Works fine for me. Are there any errors in the console (`CTRL+SHIFT+I`)?

**Comment by csss1234** [comment]
Indeed. Thanks, I didn't know how about reading the console until you prompted me : )

Plugin "no dupe leaves" is the problem, it seems. i disabled it, and Advanced URI works as expected now

```
app.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lastIndexOf')
    at wl (app.js:1:511388)
    at t._getLinkpathDest (app.js:1:2009045)
    at t.getLinkpathDest (app.js:1:2008729)
    at t.getFirstLinkpathDest (app.js:1:2008870)
    at V (plugin:no-dupe-leaves:6:1923)
    at t.eval (plugin:no-dupe-leaves:6:1212)
    at t.a [as openLinkText] (plugin:no-dupe-leaves:6:942)
    at AdvancedURI.open (plugin:obsidian-advanced-uri:4899:33)
    at Handlers.handleOpen (plugin:obsidian-advanced-uri:3975:25)
    at AdvancedURI.chooseHandler (plugin:obsidian-advanced-uri:4694:21)
    at eval (plugin:obsidian-advanced-uri:4624:12)
    at t (app.js:1:2281281)
    at <anonymous>:1:52
    at node:electron/js2c/renderer_init:2:16210
    at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:2:10422)
    at EventEmitter.emit (node:events:517:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:8536)
```
